name = "Viga3D"
uuid = "4f2ccf67-311b-48f5-bb5d-0435d0eef3ea"
authors = ["Eduardo Lenz <eduardobarplenz@gmail.com> and Sarah Maria Schroeder"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
LinearAlgebra = "1.11.0"
OrderedCollections = "1.6.3"
YAML = "0.4.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
